# Generated by Django 5.2.4 on 2025-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название категории"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
